steps:
  # 1. Instalar dependencias
  - name: 'node:20'
    entrypoint: 'npm'
    args: ['install']

  # 2. Compilar el proyecto de Angular
  - name: 'node:20'
    entrypoint: 'npm'
    args: ['run', 'build']

  # 3. Subir los archivos generados a Cloud Storage
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: 'gsutil'
    args: ['-m', 'rsync', '-r', 'dist/angular-image-uploader/browser', 'gs://frontend-jc']
